@startuml
left to right direction

:Utilisateur: as us

package Bibliothèque{
    "AjouterEmprunt" as (ae)
    "SupprimerEmprunt" as (se)
    "ChercherEmprunt" as (ce)
}

us --> ae
us --> se
us --> ce
@enduml